# Azure DevOps Pipeline for IIA Technical Tester Website
# Simplified and robust deployment to Azure Static Web Apps
# 
# Setup Instructions:
# 1. Get deployment token: az staticwebapp secrets list --name iia --resource-group iia-website --query "properties.apiKey" -o tsv
# 2. Add as secret variable in Azure Pipelines: AZURE_STATIC_WEB_APPS_API_TOKEN
# 3. Pipeline will build and deploy automatically on push to main

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - '*.md'
    - .github/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '18.x'
  staticWebAppName: 'iia'
  resourceGroup: 'iia-website'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:
  
  # Setup Node.js
  - task: NodeTool@0
    displayName: 'Install Node.js $(node_version)'
    inputs:
      versionSpec: $(node_version)
  
  # Install dependencies
  - script: npm ci
    displayName: 'Install dependencies'
  
  # Build Astro site
  - script: npm run build
    displayName: 'Build Astro site'
  
  # Run validation tests (non-blocking)
  - script: npm run test:simple
    displayName: 'Run validation tests'
    continueOnError: true
  
  # Deploy using Azure Static Web Apps CLI
  # This is more reliable than the GitHub Action
  - script: |
      npx --yes @azure/static-web-apps-cli deploy \
        --deployment-token $(AZURE_STATIC_WEB_APPS_API_TOKEN) \
        --app-location dist \
        --no-use-keychain \
        --env production
    displayName: 'Deploy to Azure Static Web Apps'
    env:
      AZURE_STATIC_WEB_APPS_API_TOKEN: $(AZURE_STATIC_WEB_APPS_API_TOKEN)